lsi: false
pygments: true

markdown: redcarpet
encoding: utf-8
port: 9000

permalink: /blog/:title

paginate_path: "blog/page:num"
paginate: 10

redcarpet:
  extensions:
    - tables
    - strikethrough
    - no_intra_emphasis
    - highlight
    - footnotes

authors:
  alext:
    displayname: Alex Tercete
    email: alex@vtex.com.br
    github: alext
    gravatar: 123
    description: "Graduado em Engenharia de Controle e Automação, é apaixonado por Software.  Entusiasta de boas práticas de programação, gosta de compartilhar seu amor."
  leandrooriente:
    displayname: Leandro Oriente
    email: leandro.oriente@vtex.com.br
    github: leandrooriente
    gravatar: 6af7a326c14b57b9c486bc4e4dec63d1
    description: "Graduado em Engenharia de Controle e Automação, é apaixonado por Software.  Entusiasta de boas práticas de programação, gosta de compartilhar seu amor."
  gadr:
    displayname: Guilherme Rodrigues
    email: guilherme@vtex.com.br
    github: gadr90
    gravatar: 123123
    description: "Graduado em Engenharia de Controle e Automação, é apaixonado por Software.  Entusiasta de boas práticas de programação, gosta de compartilhar seu amor."
  brenoc:
    displayname: Breno Calazans
    email: breno.calazans@vtex.com.br
    github: brenoc
    gravatar: 12313123
    description: "Graduado em Engenharia de Controle e Automação, é apaixonado por Software.  Entusiasta de boas práticas de programação, gosta de compartilhar seu amor."