highlighter: rouge

base_url: http://lab.vtex.com
production_url: http://lab.vtex.com

markdown: kramdown
kramdown:
  use_coderay: true
  parse_block_html: true

encoding: utf-8
port: 9000

permalink: /blog/:title

exclude:
- node_modules

paginate_path: "blog/page:num"
paginate: 10

redcarpet:
  extensions:
    - tables
    - strikethrough
    - no_intra_emphasis
    - highlight
    - footnotes

assets:
  js_compressor:  uglifier
  css_compressor: sass

tag_page_layout: tag_page
tag_page_dir: tag