-
  name: cms
  friendyName: CMS
  description: Sou o CMS
  api:
    versions:
      - latest
      - v3
      - v2
    resources:
      - configuration
      - customfiles
      - pages
      - sites
      - templates
  guide:
    - 01-google-tag-manager
-
  name: oms
  friendyName: Order Management System
  description: Sou o oms
  api:
    versions:
      - latest
    resources:
      - feed
  guide:
    - 01-marketplace-e-seller
    - 02-fluxo-do-pedido
    - 03-status-do-pedido
    - 05-consultando-pedidos
    - 06-manipulando-um-pedido
    - 07-handlers-de-pedido